name: spaceport
region: nyc
services:
  - name: spaceport
    github:
      repo: adriankuklinski/spaceport
      branch: master
      deploy_on_push: true
    source_dir: /
    dockerfile_path: infrastructure/Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
    routes:
      - path: /
    envs:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: SPACEPORT_ApplicationSettings__RequireHttps
        value: "false"
databases:
  - engine: PG
    name: blackhole
    production: false
    version: "15"
