name: cosmos
region: nyc
services:
  - name: spaceport
    github:
      branch: master
      deploy_on_push: true
      repo: adriankuklinski/Spaceport
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    source_dir: /
    dockerfile_path: infrastructure/Dockerfile
    health_check:
      http_path: /health
    routes:
      - path: /api
    envs:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: SPACEPORT_ApplicationSettings__RequireHttps
        value: "false"
      # Add this environment variable to connect to your managed database
      # The actual value will be set in the Digital Ocean dashboard or linked automatically
      - key: SPACEPORT_ConnectionStrings__DefaultConnection
        scope: RUN_AND_BUILD_TIME
        value: ${blackhole.DATABASE_URL}

databases:
  # This section lets Digital Ocean know you want to use a managed database
  # You can either create it through this config or link an existing one
  - engine: PG
    name: blackhole
    production: true  # This means it's a production database with backups
    cluster_name: blackhole
    version: "15"
