name: cosmos
region: nyc
services:
  - name: spaceport
    # Either specify GitHub source
    source_dir: /
    dockerfile_path: infrastructure/Dockerfile
    # Or specify a prebuilt image (if using GitHub Actions to build)
    # image:
    #   registry_type: DOCR
    #   repository: cosmos/spaceport
    #   tag: latest
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
    routes:
      - path: /
    envs:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: SPACEPORT_ApplicationSettings__RequireHttps
        value: "false"

# For connecting to an existing database you've already created:
# database_ref: your-database-name

# Or let App Platform create a new database:
databases:
  - engine: PG
    name: blackhole
    production: false  # Switch to true for production workloads
    version: "15"
