services:
  spaceport:
    image: spaceport:latest
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SPACEPORT_ConnectionStrings__DefaultConnection=Host=postgres;Database=blackhole;Username=admin;Password=password
      - SPACEPORT_ApplicationSettings__RequireHttps=false
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blackhole
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: