services:
  spaceport:
    image: spaceport:latest
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cosmos
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: